type blend_sfactor =
  | GL_ZERO
  | GL_ONE
  | GL_DST_COLOR
  | GL_ONE_MINUS_DST_COLOR
  | GL_SRC_ALPHA
  | GL_ONE_MINUS_SRC_ALPHA
  | GL_DST_ALPHA
  | GL_ONE_MINUS_DST_ALPHA
  | GL_SRC_ALPHA_SATURATE
