type game_mode =
  | GLUT_GAME_MODE_ACTIVE
  | GLUT_GAME_MODE_POSSIBLE
  | GLUT_GAME_MODE_WIDTH
  | GLUT_GAME_MODE_HEIGHT
  | GLUT_GAME_MODE_PIXEL_DEPTH
  | GLUT_GAME_MODE_REFRESH_RATE
  | GLUT_GAME_MODE_DISPLAY_CHANGED
