type get_boolean_1 =
  | GL_ALPHA_TEST  (** deprecated in core OpenGL 3. *)
  | GL_AUTO_NORMAL
  | GL_BLEND
  | GL_CLIP_PLANE0
  | GL_CLIP_PLANE1
  | GL_CLIP_PLANE2
  | GL_CLIP_PLANE3
  | GL_CLIP_PLANE4
  | GL_CLIP_PLANE5
  | GL_COLOR_ARRAY
  | GL_COLOR_LOGIC_OP
  | GL_COLOR_MATERIAL  (** deprecated in core OpenGL 3. *)
  | GL_COLOR_SUM
  | GL_COLOR_TABLE
  | GL_CONVOLUTION_1D
  | GL_CONVOLUTION_2D
  | GL_CULL_FACE
  | GL_CURRENT_RASTER_POSITION_VALID
  | GL_DEPTH_TEST
  | GL_DEPTH_WRITEMASK
  | GL_DITHER
  | GL_DOUBLEBUFFER
  | GL_EDGE_FLAG
  | GL_EDGE_FLAG_ARRAY
  | GL_FOG
  | GL_FOG_COORD_ARRAY
  | GL_HISTOGRAM
  | GL_INDEX_ARRAY
  | GL_INDEX_LOGIC_OP
  | GL_INDEX_MODE
  | GL_LIGHT0  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT1  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT2  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT3  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT4  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT5  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT6  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT7  (** deprecated in core OpenGL 3. *)
  | GL_LIGHTING  (** deprecated in core OpenGL 3. *)
  | GL_LIGHT_MODEL_LOCAL_VIEWER
  | GL_LIGHT_MODEL_TWO_SIDE
  | GL_LINE_SMOOTH
  | GL_LINE_STIPPLE
  | GL_MAP1_INDEX
  | GL_MAP1_NORMAL
  | GL_MAP1_TEXTURE_COORD_1
  | GL_MAP1_TEXTURE_COORD_2
  | GL_MAP1_TEXTURE_COORD_3
  | GL_MAP1_TEXTURE_COORD_4
  | GL_MAP1_VERTEX_3
  | GL_MAP1_VERTEX_4
  | GL_MAP2_COLOR_4
  | GL_MAP2_INDEX
  | GL_MAP2_NORMAL
  | GL_MAP2_TEXTURE_COORD_1
  | GL_MAP2_TEXTURE_COORD_2
  | GL_MAP2_TEXTURE_COORD_3
  | GL_MAP2_TEXTURE_COORD_4
  | GL_MAP2_VERTEX_3
  | GL_MAP2_VERTEX_4
  | GL_MAP_COLOR
  | GL_MAP_STENCIL
  | GL_MINMAX
  | GL_NORMAL_ARRAY
  | GL_NORMALIZE
  | GL_PACK_SWAP_BYTES
  | GL_POINT_SMOOTH  (** deprecated in core OpenGL 3. *)
  | GL_POINT_SPRITE  (** deprecated in core OpenGL 3. *)
  | GL_POLYGON_OFFSET_FILL
  | GL_POLYGON_OFFSET_LINE
  | GL_POLYGON_OFFSET_POINT
  | GL_POLYGON_SMOOTH
  | GL_POLYGON_STIPPLE
  | GL_POST_COLOR_MATRIX_COLOR_TABLE
  | GL_PACK_LSB_FIRST
  | GL_POST_CONVOLUTION_COLOR_TABLE
  | GL_RESCALE_NORMAL  (** deprecated in core OpenGL 3. *)
  | GL_RGBA_MODE
  | GL_SAMPLE_COVERAGE_INVERT
  | GL_SCISSOR_TEST
  | GL_SECONDARY_COLOR_ARRAY
  | GL_SEPARABLE_2D
  | GL_STENCIL_TEST
  | GL_STEREO
  | GL_TEXTURE_1D
  | GL_TEXTURE_2D
  | GL_TEXTURE_3D
  | GL_TEXTURE_COORD_ARRAY
  | GL_TEXTURE_CUBE_MAP
  | GL_TEXTURE_GEN_Q  (** deprecated in core OpenGL 3. *)
  | GL_TEXTURE_GEN_R  (** deprecated in core OpenGL 3. *)
  | GL_TEXTURE_GEN_S  (** deprecated in core OpenGL 3. *)
  | GL_TEXTURE_GEN_T  (** deprecated in core OpenGL 3. *)
  | GL_UNPACK_LSB_FIRST
  | GL_UNPACK_SWAP_BYTES
  | GL_VERTEX_ARRAY
  | GL_VERTEX_PROGRAM_POINT_SIZE
  | GL_VERTEX_PROGRAM_TWO_SIDE  (** deprecated in core OpenGL 3. *)
  | GL_PACK_ALIGNMENT
  | GL_PACK_IMAGE_HEIGHT
  | GL_PACK_ROW_LENGTH
  | GL_PACK_SKIP_IMAGES
  | GL_PACK_SKIP_PIXELS
  | GL_PACK_SKIP_ROWS
  | GL_UNPACK_IMAGE_HEIGHT
  | GL_UNPACK_ROW_LENGTH
  | GL_UNPACK_SKIP_IMAGES
  | GL_UNPACK_SKIP_PIXELS
  | GL_UNPACK_SKIP_ROWS
