type get_matrix =
  | GL_COLOR_MATRIX
  | GL_MODELVIEW_MATRIX
  | GL_PROJECTION_MATRIX
  | GL_TEXTURE_MATRIX
  | GL_TRANSPOSE_COLOR_MATRIX
  | GL_TRANSPOSE_MODELVIEW_MATRIX
  | GL_TRANSPOSE_PROJECTION_MATRIX
  | GL_TRANSPOSE_TEXTURE_MATRIX
