type glut_device =
  | GLUT_HAS_KEYBOARD
  | GLUT_HAS_MOUSE
  | GLUT_HAS_SPACEBALL
  | GLUT_HAS_DIAL_AND_BUTTON_BOX
  | GLUT_HAS_TABLET
  | GLUT_NUM_MOUSE_BUTTONS
  | GLUT_NUM_SPACEBALL_BUTTONS
  | GLUT_NUM_BUTTON_BOX_BUTTONS
  | GLUT_NUM_DIALS
  | GLUT_NUM_TABLET_BUTTONS
