type init_mode =
  | GLUT_RGBA
  | GLUT_RGB
  | GLUT_INDEX
  | GLUT_SINGLE
  | GLUT_DOUBLE
  | GLUT_ACCUM
  | GLUT_ALPHA
  | GLUT_DEPTH
  | GLUT_STENCIL
  | GLUT_MULTISAMPLE
  | GLUT_STEREO
  | GLUT_LUMINANCE
