type map1_target =
  | GL_MAP1_VERTEX_3
  | GL_MAP1_VERTEX_4
  | GL_MAP1_INDEX
  | GL_MAP1_COLOR_4
  | GL_MAP1_NORMAL
  | GL_MAP1_TEXTURE_COORD_1
  | GL_MAP1_TEXTURE_COORD_2
  | GL_MAP1_TEXTURE_COORD_3
  | GL_MAP1_TEXTURE_COORD_4
