type map2_target =
  | GL_MAP2_VERTEX_3
  | GL_MAP2_VERTEX_4
  | GL_MAP2_INDEX
  | GL_MAP2_COLOR_4
  | GL_MAP2_NORMAL
  | GL_MAP2_TEXTURE_COORD_1
  | GL_MAP2_TEXTURE_COORD_2
  | GL_MAP2_TEXTURE_COORD_3
  | GL_MAP2_TEXTURE_COORD_4
