  static const GLenum conv_pixel_transfer_f_ARB_table[] = {
    GL_POST_COLOR_MATRIX_RED_SCALE,
    GL_POST_COLOR_MATRIX_GREEN_SCALE,
    GL_POST_COLOR_MATRIX_BLUE_SCALE,
    GL_POST_COLOR_MATRIX_ALPHA_SCALE,
    GL_POST_COLOR_MATRIX_RED_BIAS,
    GL_POST_COLOR_MATRIX_GREEN_BIAS,
    GL_POST_COLOR_MATRIX_BLUE_BIAS,
    GL_POST_COLOR_MATRIX_ALPHA_BIAS,
    GL_POST_CONVOLUTION_RED_SCALE,
    GL_POST_CONVOLUTION_GREEN_SCALE,
    GL_POST_CONVOLUTION_BLUE_SCALE,
    GL_POST_CONVOLUTION_ALPHA_SCALE,
    GL_POST_CONVOLUTION_RED_BIAS,
    GL_POST_CONVOLUTION_GREEN_BIAS,
    GL_POST_CONVOLUTION_BLUE_BIAS,
    GL_POST_CONVOLUTION_ALPHA_BIAS,
  };
  pixel_transfer_f_ARB = conv_pixel_transfer_f_ARB_table[Int_val(_pixel_transfer_f_ARB)];
#if defined(USE_MY_GL3_CORE_PROFILE)
  if (pixel_transfer_f_ARB == 0x000A)
    caml_failwith("using gl-enum deprecated in core OpenGL 3");
#endif
