type pixel_packing_i =
  | GL_PACK_ROW_LENGTH
  | GL_PACK_IMAGE_HEIGHT
  | GL_PACK_SKIP_PIXELS
  | GL_PACK_SKIP_ROWS
  | GL_PACK_SKIP_IMAGES
  | GL_PACK_ALIGNMENT
  | GL_UNPACK_ROW_LENGTH
  | GL_UNPACK_IMAGE_HEIGHT
  | GL_UNPACK_SKIP_PIXELS
  | GL_UNPACK_SKIP_ROWS
  | GL_UNPACK_SKIP_IMAGES
  | GL_UNPACK_ALIGNMENT
