type pixel_map =
  | GL_PIXEL_MAP_I_TO_I
  | GL_PIXEL_MAP_S_TO_S
  | GL_PIXEL_MAP_I_TO_R
  | GL_PIXEL_MAP_I_TO_G
  | GL_PIXEL_MAP_I_TO_B
  | GL_PIXEL_MAP_I_TO_A
  | GL_PIXEL_MAP_R_TO_R
  | GL_PIXEL_MAP_G_TO_G
  | GL_PIXEL_MAP_B_TO_B
  | GL_PIXEL_MAP_A_TO_A
