type pixel_transfer_f_ARB =
  | GL_POST_COLOR_MATRIX_RED_SCALE
  | GL_POST_COLOR_MATRIX_GREEN_SCALE
  | GL_POST_COLOR_MATRIX_BLUE_SCALE
  | GL_POST_COLOR_MATRIX_ALPHA_SCALE
  | GL_POST_COLOR_MATRIX_RED_BIAS
  | GL_POST_COLOR_MATRIX_GREEN_BIAS
  | GL_POST_COLOR_MATRIX_BLUE_BIAS
  | GL_POST_COLOR_MATRIX_ALPHA_BIAS
  | GL_POST_CONVOLUTION_RED_SCALE
  | GL_POST_CONVOLUTION_GREEN_SCALE
  | GL_POST_CONVOLUTION_BLUE_SCALE
  | GL_POST_CONVOLUTION_ALPHA_SCALE
  | GL_POST_CONVOLUTION_RED_BIAS
  | GL_POST_CONVOLUTION_GREEN_BIAS
  | GL_POST_CONVOLUTION_BLUE_BIAS
  | GL_POST_CONVOLUTION_ALPHA_BIAS
