type target_2d =
  | GL_TEXTURE_2D
  | GL_PROXY_TEXTURE_2D
  | GL_TEXTURE_CUBE_MAP_POSITIVE_X
  | GL_TEXTURE_CUBE_MAP_NEGATIVE_X
  | GL_TEXTURE_CUBE_MAP_POSITIVE_Y
  | GL_TEXTURE_CUBE_MAP_NEGATIVE_Y
  | GL_TEXTURE_CUBE_MAP_POSITIVE_Z
  | GL_TEXTURE_CUBE_MAP_NEGATIVE_Z
  | GL_PROXY_TEXTURE_CUBE_MAP
